otterize/credentials-operator

src/operator/controllers/otterizeclient/client.go
src/operator/controllers/otterizeclient/otterizegraphql/generated.go
src/operator/controllers/otterizeclient/otterizegraphql/genqlient.graphql

Use the standard way to query service (instead of using the mocked endpoint)

unmock service query

---

src/operator/controllers/otterizeclient/status_report.go

To make the component appear as connected right when it is up, this PR send the connection right when operator is up, since there is no reason to wait.

Report component status on connection

---

src/operator/controllers/otterizeclient/client.go
src/operator/controllers/otterizeclient/otterizegraphql/generated.go
src/operator/controllers/otterizeclient/otterizegraphql/genqlient.graphql

Use otterize-cloud's RemoveOrphanedCertificateRequests for implementing CleanupOrphanK8SPodEntries on Otterize's CloudClient
No test because it is just an implementation of the interface. (tested on the cloud side)

Implement CleanupOrphanK8SPodEntries on Otterize's CloudClient

---

src/operator/controllers/pod_controller.go
src/operator/controllers/pod_controller_test.go
src/operator/main.go

For otterize-cloud integration - add the option of not register every pod but only those which ask for a secret
added a test for r`egisterOnlyPodsWithSecretAnnotation=true`

Add the option to register only pods with secret annotations

---

.github/workflows/build.yaml
.github/workflows/release-tag.yaml

Publish the docker image to credentials-operator instead of spire-integration.

Publish docker image to credentials-operator instead of spire-integration

---

src/operator/controllers/otterizeclient/config.go

The default config value for API address was missing the `/api` suffix - now corrected

Fix default API address

---

src/operator/controllers/otterizeclient/client.go

When the operator doesn't find pod owners for `ReportActiveCertificateRequesters` it sends a nil value. This PR initialize the slice to non-nil value and also skip the API call since the backend has nothing to do if the list is empty.

Fix bug: Sending nil when no namespaced pod owners found

---

src/operator/controllers/metadata/annotations.go
src/operator/controllers/service_account_pod/service_account_pod_reconciler.go
src/operator/controllers/service_account_pod/service_account_pod_reconciler_test.go

Since pods cannot be created when their assigned SA doesn't exist, I deleted the "create SA" functionality. Instead, we will just label the pre-existing service account when the pod is annotated with an "I want IAM role" annotation.

AWS IAM integration - label service account instead of creating it.

---

.github/workflows/build.yaml

Telemetry events should be sent with application version, this PR add using version on build action as Github run id like all other repos do

Add version variable to Github build action

---

src/operator/controllers/aws_iam/serviceaccount/serviceaccount_controller.go
src/operator/controllers/aws_iam/webhooks/pod_webhook.go
src/operator/main.go

Before this PR, the credentials operator logged in key=value format, as the logger was misconfigured. This PR causes it to log in JSON format, like the intents operator and network mapper.

Configure logger to use JSON format

---

src/operator/main.go

Prior to this PR, you had to set certificateProvider=otterize-cloud in order to use the username and password capabilities of the credentials operator. But username and passwords are not certificates, so this PR makes it so you just need to enable cloud instead.

PostgreSQL: Username and password no longer erroneously require certificate provider = cloud to be selected

---

src/operator/controllers/certificates/otterizecertgen/otterize_certificate_generator.go
src/operator/controllers/certificates/otterizecertgen/otterize_certificate_generator_test.go

When using the Otterize Cloud certificate generator, filter out any empty PEMs generated by it before encoding them to a cert CA chain. 
This is done to support removing intermediate CA generation from Otterize Cloud.

Filter out empty PEMs from cert chain to support no intermediate CA generation

---

src/operator/main.go

Before this PR, it was only possible to use one of the AWS/GCP/Azure integrations on the same cluster. Trying to use both AWS and one of the other two would replace the webhook handler and as a result, would not work.
Accompanies https://github.com/otterize/helm-charts/pull/192

Fix issue running AWS webhooks alongside GCP and Azure simultaneously

---

src/operator/controllers/intents/reconciler.go
src/operator/go.mod
src/operator/go.sum

Fixing code due to removed CRD field
Include any links supporting this change such as a:
- GitHub Issue/PR number addressed or fixed
- StackOverflow post
- Related pull requests/issues from other repos
If there are no references, simply delete this section.

Code fix due to removed CRD field

---

src/operator/Dockerfile

User $BUILDPLATFORM in build stage in Dockerfile: This will cause the builder image to be arm64 on Macs, and amd64 on CI and other environments.
Not cross-compiling arm64->amd64 on macs is significantly faster. The resulting images are without change.
https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/

Use $BUILDPLATFORM in Dockerfile

---

src/operator/controllers/intents/database_user_reconciler.go

Prior to this PR, the database user reconciler would erroneously report ErrPodNotFound, even though it's safe to stop and let the reconciler be called again, as the pod has been terminated already.

Fixed bug where harmless pod not found errors would be erroneously reported for pods that have already terminated during DB user reconciler flow

---

src/operator/main.go

Before this PR, the credentials operator could not start before the intents operator. This is problematic if the intents operator is set up to access Kafka, which requires that the credentials operator provision a mTLS volume for it.

Ensure CRDs in credentials operator to allow creds operator to start before intents operator with no CRDs in Helm chart

---

.github/workflows/build.yaml
src/operator/controllers/poduserpassword/db_credentials_pod_reconciler.go
src/operator/go.mod
src/operator/go.sum
src/operator/main.go

- Support reading database credentials for PostgreSQL & MySQL, from a k8s secret, referenced by their database ServerConfig. 
- Implement backwards compatibility with existing database ServerConfigs, with fallback to plaintext username & password specified in the ServerConfig. 
- Call E2E tests workflow from https://github.com/otterize/helm-charts on build workflow
https://github.com/otterize/helm-charts/pull/218
https://github.com/otterize/intents-operator/pull/440
https://github.com/otterize/credentials-operator/pull/143
https://github.com/otterize/docs/pull/243

Support reading database ServerConfig credentials from k8s secrets

---

src/operator/controllers/metadata/annotations.go
src/operator/controllers/poduserpassword/db_credentials_pod_reconciler.go
src/operator/go.mod
src/operator/go.sum

* The credentials-operator can now restart pods when their secrets are being rotated (or created fresh) if an annotation is present on the pod
* It also watches secrets in the cluster, and if certain conditions are met (secret is deleting) - will trigger pod reconciliation. This enables users to manually trigger secret rotation by simply deleting a secret.

Enabling the credentials operator to restart pods after secret rotation/creation based on pod annotations

---

src/operator/controllers/poduserpassword/db_credentials_pod_reconciler.go

Fixing get secret returning "not found" shortly after create.
Also changed flow to always ensure password in databases, but only trigger pod restart after we created a new secret.

Fixing get secret returning "not found" shortly after create

---

src/operator/controllers/certificates/jks/jks.go
src/operator/controllers/certmanageradapter/approver.go
src/operator/controllers/iam/iamcredentialsagents/awscredentialsagent/agent.go
src/operator/controllers/iam/pods/pods_controller.go
src/operator/controllers/iam/serviceaccounts/serviceaccount_controller.go
src/operator/controllers/iam/webhooks/pod_webhook.go
src/operator/controllers/otterizeclient/client.go
src/operator/controllers/secrets/base.go
src/operator/controllers/secrets/manager.go
src/operator/controllers/secrets/types/secret_types.go
src/operator/controllers/spireclient/entries/registry.go
src/operator/controllers/spireclient/svids/store.go
src/operator/controllers/tls_pod/tls_pod_reconciler.go

Replace usage of `fmt.Errorf` with our internal `errors.Errorf` implementation, to ensure that errors are reported with full stack traces.

Fix error reporting missing stack trace due to using fmt.Errorf rather than errors.Errorf

---

src/operator/controllers/poduserpassword/db_credentials_pod_reconciler.go
src/operator/go.mod
src/operator/go.sum
src/operator/main.go

In this pull request, we add support to the new API versions.
https://github.com/otterize/intents-operator/pull/439

Support the new API versions of Otterize's CRD: `v1` and `v2alpha1`

---

src/operator/go.mod
src/operator/go.sum
src/operator/main.go

After reconsidering Kubernetes custom resources versioning conventions, we have decided to upgrade `v1alpha3` to `v1beta1` instead of `v1`
https://github.com/otterize/intents-operator/pull/454/

Update Otterize CRD versions following changes to the intents operator

---

src/operator/main.go
src/operator/operatorconfig/config.go

Secret rotation is now disabled by default and can be enabled via the relevant field in the operator's `values.yaml`. 
[Helm chart PR](https://github.com/otterize/helm-charts/pull/236)

Disabling secret rotation by default and adding relevant flag

---

src/operator/go.mod
src/operator/go.sum

Bump github.com/otterize/intents-operator/src dependency to latest main version. 

Bump intents-operator version to latest main

---

src/operator/controllers/iam/pods/pods_controller.go
src/operator/controllers/iam/serviceaccounts/serviceaccount_controller.go
src/operator/controllers/iam/webhooks/pod_webhook.go
src/operator/controllers/poduserpassword/db_credentials_pod_reconciler.go

This PR fixes a bug in the operator, in which updating pod labels and annotations sometimes failed due to unexpected changes being detected in the pod's containers. 
This is resolved by using StrategicMergeFrom rather than (plain) MergeFrom, which applies updates as strategic patches rather than complete overrides. 

Avoid attempting to override pod containers when updating labels & annotations

---

src/operator/controllers/iam/iamcredentialsagents/awscredentialsagent/agent.go

This PR enhances the credentials-operator's support for AWS roles anywhere, by exposing the AWS role, trust profile & trust anchor ARNs as environment variables, as well as the paths to the private key and cert files generated for that role. This should be used by client containers to obtain temporary security credentials, using the AWS signing helper tool, or using temporary credentials generation with https://github.com/aws/rolesanywhere-credential-helper . 
See https://github.com/otterize/intents-operator/blob/main/src/shared/awsagent/rolesanywhere_creds/credentials_provider.go for a usage example. 
https://docs.aws.amazon.com/rolesanywhere/latest/userguide/credential-helper.html

Expose AWS roles anywhere arguments as env vars, so that client containers can use them to obtain temporary security credentials

---

src/operator/controllers/iam/pods/pods_controller.go
src/operator/controllers/iam/serviceaccounts/serviceaccount_controller.go

This PR fixes AWS API errors NotFound and Forbidden, that may happen on pods & SAs running on EKS, while the operator attempts to cleanup finalizers applied on them. 
These errors can happen because the service account is already being deleted, and re-queueing should solve them all in a clean way.

Fix NotFound and Forbidden errors happening on AWS EKS pods and SAs during cleanup

---

src/operator/controllers/poduserpassword/db_credentials_pod_reconciler.go

Before this PR, when a Secret already existed, the operator would report an error and retry. Now, it only retries, as this can happen under normal circumstances.

Handle issue where DB secret already exists by requeueing and restarting the flow

---

src/operator/controllers/poduserpassword/db_credentials_pod_reconciler.go

This PR fixes a buggy error report in the database credentials reconcile loop, when attempting to reconcile on an already deleted namespace.

Bugfix on DB credentials reconciler: ignore NotFound errors on querying namespaces

---

src/operator/controllers/iam/pods/pods_controller.go
src/operator/controllers/iam/serviceaccounts/serviceaccount_controller.go
src/operator/controllers/iam/webhooks/pod_webhook.go
src/operator/controllers/tls_pod/tls_pod_reconciler.go

This PR fixes an issue with handling Kubernetes API 'Forbidden' errors during update, which are being wrongly reported as errors in the logs and on the Kubernetes resource. These errors are expected during the normal workflow of a reconciler, e.g. when the resource in question is already being deleted. They should be caught and the flow should be requeued (similar to 'Conflict' errors). 
Also include details of the environment this PR …

Fix Kubernetes API 'Forbidden' errors during update, being wrongly reported as errors on the resource

---

src/operator/controllers/iam/pods/pods_controller.go

A possible race condition exists when deleting an object using foregroundDeletion. It is possible when deleting an object with children using foregroundDeletion, for the watcher to have a different knowledge of the finalizer list than the API server that receives the Patch request, i.e. the watcher sees the foregroundDeletion finalizer, but the server that accepts the patch request doesn't so it looks like it was added. Using StrategicMergeFrom creates a proper patch instead of replacing the list, which solves the issue.
Additionally, ignore errors for invalid patches while cleaning up.
Very similar bug: https://github.com/kubernetes/kubernetes/issues/111643

Use StrategicMergeFrom to update finalizers

---

src/operator/controllers/iam/webhooks/pod_webhook.go

Please see the [contributing guidelines](CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo. This template is based on Auth0's excellent template.
Adding call to error unwrap so we could compare with k8s errors. Beforehand we would compare with a wrapped error which would never "hit" the Kubernetes `IsError()` functions

Adding call to error unwrap so we could compare with k8s errors

---

src/operator/controllers/iam/serviceaccounts/serviceaccount_controller.go
src/operator/controllers/iam/serviceaccounts/serviceaccount_controller_test.go

Perform service account cleanup only once it is deleted to avoid race conditions on pod restarts.

Cleanup IAM identities on service account deletion

---

src/operator/controllers/tls_pod/tls_pod_reconciler.go
src/operator/controllers/tls_pod/tls_pod_reconciler_test.go

Changed update pod label to use patch

Changed update pod label to use patch

---

src/operator/controllers/iam/iamcredentialsagents/awscredentialsagent/agent.go
src/operator/controllers/iam/pods/pods_controller.go
src/operator/controllers/iam/pods/pods_controller_test.go
src/operator/controllers/iam/webhooks/pod_webhook.go
src/operator/controllers/metadata/labels.go
src/operator/shared/apiutils/pods.go

- Improve AWS IAM integration debug logging to ease troubleshooting around unexpected role creation: add debug- or info-level logging around IAM-related updates of pods and service accounts
- Remove redundant labeling of service account on last pod terminating in AWS IAM integration, which is no longer used and is just a cause for potential conflicts. 
https://github.com/otterize/credentials-operator/pull/171

Improve AWS IAM integration debug logging to improve diagnostics for role creation

---

src/operator/controllers/iam/iamcredentialsagents/awscredentialsagent/multi_account_aws_credentials_agent.go
src/operator/go.mod
src/operator/go.sum

This PR fixes an issue with the AWS IAM integration, where pods labeled with `credentials-operator.otterize.com/create-aws-role` were assigned an Otterize-generated IAM role, ignoring the label value. Meaning that if a pod was labeled with `credentials-operator.otterize.com/create-aws-role=false`, the integration would still create and assign an IAM role for it, possibly overriding any other user-managed role assigned to it. 
https://github.com/otterize/credentials-operator/pull/178
https://github.com/otterize/intents-operator/pull/549

Fix bug where AWS IAM roles could be created for a particular workload even when disabled for that particular workload

---

src/operator/go.mod
src/operator/go.sum
src/operator/main.go

We have revamped the format for ClientIntents to make them easier to understand and make it possible to generate more restrictive policies by default. [Read more on the docs >>](https://docs.otterize.com/reference/ClientIntents%20CRD/migrateToV2)
The two primary changes is that the word `service` is no longer used, except to mean a Kubernetes Service; before, it could mean an Otterize Service or a Kubernetes Service, which was confusing. Instead, we now use `workload` . `calls` have also been renamed `targets` , and many smaller changes to the structure to improve
What happens to your existing ClientIntents? Don’t worry, the change is backwards compatible, and nothing changes unless you explicitly upgrade. If you’re a customer, we’ll reach out to explain and plan together. If you’re using …

Support new API version for ClientIntents: v2beta1

---

src/operator/config/rbac/role.yaml
src/operator/go.mod
src/operator/go.sum
src/operator/main.go
src/operator/operatorconfig/config.go

Added support for reusing the webhook TLS certificate across different deployments to prevent cases where operator takes too long to start up
https://github.com/otterize/intents-operator/pull/560
https://github.com/otterize/intents-operator/pull/565

Added support for reusing the webhook TLS certificate across different deployments to prevent cases where operator takes too long to start up

---

src/operator/main.go

Fix credentials-operator webhook malfunctioning due to wrong self-signed certificate hostname
Follow-up on https://github.com/otterize/credentials-operator/pull/180

Fix credentials-operator webhook malfunctioning due to wrong self-signed certificate hostname

---

src/operator/go.mod
src/operator/go.sum
src/operator/main.go
src/operator/operatorconfig/config.go

Fix issue in webhook cert persistency using secrets, where the credentials-operator secret name was wrong due to use of configuration. Instead, use fixed secret names.

Fix issue in webhook cert persistency where credentials-operator secret name was wrong due to use of configuration
